config/routes.rb
Rails.application.routes.draw do

  root :to => 'homes#top', as: 'root'
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users
  resources :books, only: [:new, :index, :show, :create, :destroy, :edit, :update]
  resources :users, only: [:create, :show, :edit, :update, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :title, presence: true, if: :creating?
  validates :title, presence: true, if: :editing?
  
  validates :body, presence: true, if: :creating?
  validates :body, presence: true, if: :editing?
  validates :body, length: { in: 0..200 }
  
  def get_book
    if title.attached?
      title
    end
  end

  def creating?
    new_record?
  end
  
  def editing?
    !new_record?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

def login
  @login || self.name || self.email
end
  # このメソッドを追加して、ログインに名前かメールアドレスのいずれかを使えるようにする
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup

    # loginというパラメータでusername（name）かemailを使えるようにする
    if login = conditions.delete(:login)
      # usernameかemailで検索する
      where(conditions).where(["username = :value OR email = :value", { :value => login }]).first
    else
      where(conditions).first
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource) 
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      error_messages = "#{@book.errors.count} errors prohibited this obj from being saved:<br>" +
      @book.errors.full_messages.map { |msg| "・#{msg}" }.join("<br>")
      flash[:alert] = error_messages.html_safe
      redirect_to books_path
    end
  end

  def update
    is_matching_login_book
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def edit
    is_matching_login_book
    @book = Book.find(params[:id])
  end

  def index
   @books = Book.all
   @book = Book.new
  end

  def show
    @book_detail= Book.find(params[:id])
    @book = Book.new
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_book
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @users = User.all
    @books = Book.all
    @book = Book.new
  end
  
  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def index
 
    @users = User.all
    @book = Book.new
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<h1>Books</h1>
<table>
<tr><th>Title </th><th> Opinion</th></tr>
<% books.each do |book| %>
<% if book.user.id == user.id %>
  <div>
    <td><span class="book-title"><p><%= link_to "#{book.user.name}", user_path(book.user.id) %></p></td>
    <td><span class="book-title"><p><%= link_to "#{book.title}", book_path(book.id) %></p></td>
    <td><span class="book-title"><p><%= book.body %></p></td>
  </tr>
  </div>
  <% end %>
<% end %>
</table>

app/views/books/_new.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf8" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="style.css" />
</head>

<div class="container">
  <div class="row">
    <h1>New book</h1>
    <%= form_with model: book do |f| %>
      <h6>Title</h6>
      <%= f.text_field :title %>
      <h6>Opinion</h6>
      <%= f.text_area :body %><br>
      <%= f.submit 'Create Book',  class: "btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css" />
  </head>

  <main>
    <body>
      <div class="container">
        <div class="row justify-content-center">
          <div class="d-flex justify-content-start m-3">
            <% if @book.errors.any? %>
              <% if @book.errors.count == 1 %>
                <%= @book.errors.count %> error prohibited this obj from being saved:
              <% else %>
                <%= @book.errors.count %> errors prohibited this obj from being saved:
              <% end %>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>

        <div class="row justify-content-center">
          <div class="d-flex justify-content-center w-100">
            <h2>Editing Book</h2>
          </div>
        </div>
        <%= form_with model: @book do |f| %>
          <div class="row justify-content-center">
            <div class="d-flex justify-content-start">
              <label>Title</label>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="d-flex justify-content-center w-100">
            <%= f.text_field :title, autofocus: true, id:"inputTitle" %>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="d-flex justify-content-center w-100">
              <label>Opinion</label><br>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="d-flex justify-content-center w-100">
              <%= f.text_area :body, autofocus: true, id:"inputTitle" %>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="d-flex justify-content-center w-100 m-4">
              <%= f.submit "Update Book", class: "btn btn-success" %>
            </div>
          </div>
            <div class="row justify-content-center">
              <div class="d-flex justify-content-center w-100 m-4">
              <p>
                <span class="book-title"><%= link_to "Show", book_path(@book.id) %> |
                <span class="book-title"><%= link_to "Back", books_path %>
              </p>
            </div>
          </div>
        <% end %>
      </div>
    </body>
  </main>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css" />
  </head>

<main>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
          <%= render partial: 'users/show', locals: { user: @user }%>
          <%= render partial: 'books/new', locals: { book: @book }%>
      </div>
      <div class="col-md-8 offset-md-1" >
        <h1 class="m-4">Books</h1>
        <table class="table">
            <tr>
              <th> </th>
              <th>Title </th>
              <th> Opinion</th>
            </tr>
            <% @books.each do |book| %>
                  <% if book.user.profile_image.attached? %>
                    <td>
                    <%= link_to user_path(book.user.id), onclick: "event.stopPropagation();" do %>
                      <span class="book-title"><p><%= image_tag book.user.get_profile_image(100,100) %></p>
                    <% end %>
                    </td>
                  <% else %>
                    <td>
                    <%= link_to user_path(book.user.id), onclick: "event.stopPropagation();" do %>
                    <span class="book-title"><p><%= image_tag 'no_image', size: '100x100' %></p>
                    <% end %>
                    </td>
                  <% end %>
                  <td><span class="book-title"><p><%= link_to "#{book.title}", book_path(book.id), onclick: "event.stopPropagation();" %></p></td>
                  <td><span class="book-title"><p><%= book.body %></p></td>
                </tr>
            <% end %>
        </table>
      </div>
    </div>
  </div>
  </body>
</main>
</html>
 

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
    <%= f.text_field :title %>
  <h4>Opinion</h4>
    <%= f.text_area :body %><br>
    <%= f.submit 'Create Book',  class: "btn btn-success"%>
<% end %>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css" />
  </head>

  <main>
    <body>
      <div class="container"> 
        <div class ="row">
          <div class ="col-md-3">
            <h1 class ="m-4">User info</h1>
              <% if @book_detail.user.profile_image.attached? %>
                <p><%= image_tag @book_detail.user.get_profile_image(100,100) %></p>
              <% else %>
                <p><%= image_tag 'no_image', size: '100x100' %></p>
              <% end %>
            <h3>name<%= @book_detail.user.name %></h3>
            <h3>introduction  <%= @book_detail.user.introduction %></h3>
            <%= link_to edit_user_path(@book_detail.user.id), class: "btn btn-outline-secondary btn w-50" do %>
              <i class="fa-solid fa-user-gear"></i>
              <% end %>
          <%= render partial: 'books/new', locals: { book: @book }%>
        </div>

          <div class="col-md-8 offset-md-1">
            <h1 class="m-4">Book detail</h1>
              <table class="table">
                <tr>
                  <td>
                    <%= link_to user_path(@book_detail.user.id), onclick: "event.stopPropagation();" do %>
                    <span class="book-title"><p><%= image_tag @book_detail.user.get_profile_image(100,100) %></p>
                    <% end %>
                  <td>
                  <td><span class="book-title"><p><%= link_to "#{@book_detail.user.name}", user_path(@book_detail.user.id) %></p></td>
                  <td><span class="book-title"><p><%= @book_detail.title %></p></td>
                  <td><span class="book-title"><p><%= @book_detail.body %></p></td>
                  
                  <% if @book_detail.user == current_user %>
                    <td><span class="book-title"><%= link_to "Edit", edit_book_path(@book_detail), class: "btn btn-success" %></td>
                    <td><span class="book-title"><%= link_to "Destroy", book_path(@book_detail.id), method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-danger" %></td>
                  <% end %>
                </tr>
            </table>
          </div>
        </div>
      </div>
    </body>
  </main>
</html>

app/views/homes/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css" />
  </head>

  <main>
    <body>
      <div class="container">
        <div class="row">
          <div class="col d-flex justify-content-center m-4">
              <h1>Welcome to <i class="fa-solid fa-book fa-lg"></i>Bookers!</h1>
          </div>
        </div>
      </div>
    </body>
  </main>
</html>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf8" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="style.css" />
</head>

  <body>
  <div class="container">
    <div class="row justify-content-center">
      <div class="d-flex justify-content-start m-3">
        <h1>welcome to <i class="fa-solid fa-book fa-lg"></i>Bookers! </>
      </div>
    </div>
    <div class="row justify-content-center w-100">
      <div class="d-flex justify-content-start m-3">
        <p>In <i class="fa-solid fa-book fa-lg"></i>Bookers,<br>
          you can share and exchange your opinions , inpressions , and emotions<br>
          about various books!<br>
        </p>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="d-flex justify-content-center w-100">
        <%= link_to "Log in", new_user_session_path, class: "btn-sm btn-info btn w-50 m-3" %><br>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="d-flex justify-content-center w-100">
        <%= link_to "Sign up", new_user_registration_path, class: "btn-sm btn-success btn w-50 m-3" %>
      </div>
    </div>
  </body>
</div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <script src="https://kit.fontawesome.com/e3debef22c.js" crossorigin="anonymous"></script>
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-1">
          <ul class="navbar-brand">
             <%= link_to "Bookers", root_path, class: "nav-link text-light" %>
          </ul>
          <div class="container-fluid">
            <ul class="navbar-nav ml-auto">
              <div style="display: flex; align-items: center;">
                  <i class="fa-solid fa-house" style="color: #ffffff;"></i><%= link_to "Home", user_path(current_user), class: "nav-link text-light" %>
            </div>
            <ul class="navbar-nav ml-auto">
              <div style="display: flex; align-items: center;">
                <i class="fa-solid fa-users", style="color: #ffffff;"></i><%= link_to "Users", users_path, class: "nav-link text-light" %>
              </div>
            </ul>
            <ul class="navbar-nav ml-auto">
              <div style="display: flex; align-items: center;">
                <i class="fa-solid fa-book-open", style="color: #ffffff;"></i><%= link_to "Books", books_path, class: "nav-link text-light" %>
              </div>
            </ul>
            <ul class="navbar-nav ml-auto">
              <div style="display: flex; align-items: center;">
                <i class="fa-solid fa-right-from-bracket", style="color: #ffffff;"></i><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
              </div>
            </ul>
          </div>
        </nav>
      <% else %>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-1">
          <ul class="navbar-brand">
             <%= link_to "Bookers", root_path, class: "nav-link text-light" %>
          </ul>
          <div class="container-fluid">
            <ul class="navbar-nav ml-auto">
              <div style="display: flex; align-items: center;">
                  <i class="fa-solid fa-house" style="color: #ffffff;"></i><%= link_to "Home", root_path, class: "nav-link text-light" %>
            <ul class="navbar-nav ml-auto">
              <div style="display: flex; align-items: center;">
                  <i class="fa-solid fa-link" style="color: #ffffff;"></i><%= link_to "About", about_path, class: "nav-link text-light" %>
            <ul class="navbar-nav ml-auto">
              <div style="display: flex; align-items: center;">
                  <i class="fa-solid fa-user-plus" style="color: #ffffff;" ></i><%= link_to "Sign up", new_user_registration_path, class: "nav-link text-light" %>
            <ul class="navbar-nav ml-auto">
              <div style="display: flex; align-items: center;">
                  <i class="fa-solid fa-right-to-bracket" style="color: #ffffff;" ></i><%= link_to "Log in", new_user_session_path, class: "nav-link text-light" %>
          </div>
        </nav>
      <% end %>
    </header>
    
    <% unless (controller_name == "sessions" && action_name == "new") %> 
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>">
          <%= message.html_safe %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
  </body>

  
    <div class="d-flex justify-content-center">
    <footer>
      CopyRight Infratop.inc
    </footer>
    </div>
  
</html>

app/views/users/_index.html.erb
<h1>Users</h1>
<table>
  <tr><th> image </th><th> name </th></tr>
  <% @users.each do |user| %>
    <div>
        <td><span class="book-title"><p><%= image_tag user.get_profile_image(100,100) %></p></td>
        <td><span class="book-title"><p><p><%= user.name %></p></td>
        <td><span class="book-title"><p><%= link_to "Show", user_path(user.id) %></p></td>
    </div>
<table>

<% end %>

app/views/users/_show.html.erb
<% if user_signed_in? %>
  <div>
    <div class="container mt-3">
    <h1 class="w-100 m-4">User Info</h1>
      <% if current_user.profile_image.attached? %>
        <p class="w-100 m-4"><%= image_tag current_user.get_profile_image(100,100) %></p>
      <% else %>
        <p><%= image_tag 'no_image', size: '100x100' %></p>
      <% end %>
        <h6 class="w-100 m-4">name<span class="text-body"><%= current_user.name %></span></h6>
        <h6 class="w-100 m-4">introduction  <span class="text-body"><%= current_user.introduction %></span></h6>
      <%= link_to edit_user_path(current_user.id),class: "btn btn-outline-secondary btn w-50" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>  
    </div>
  </div>
<% end %> 

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css" />
  </head>

  <main>
    <body>
      <div class="container">
        <div class="row justify-content-center">
          <div class="d-flex justify-content-start m-3">
             <h2>User info</h2>
          </div>
        </div>
        <div class="row">
          <div class="d-flex justify-content-start m-3">  
            <% if @user.errors.any? %>
              <% if @user.errors.count == 1 %>
                <%= @user.errors.count %> error prohibited this obj from being saved:
              <% else %>
                <%= @user.errors.count %> errors prohibited this obj from being saved:
              <% end %>
                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
            <% end %>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="d-flex justify-content-start m-3">  
            <%= form_with model: @user do |f| %>  
              <h6>
                <label for="inputName">Name</label><br>
                <%= f.text_field :name, autofocus: true, id:"inputName" %>
              </h6>
              <h6>
                <label for="inputImage">Image</label><br>
                <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
              </h6>
              <h6>  
                <label for="inputIntroduction">Introduction</label><br>
                <%= f.text_area :introduction, autofocus: true, id:"inputName" %><br>
              </h6>
              <h6>
                <%= f.submit "Update User", class: "btn btn-secondary" %>
              </h6>
            <% end %>
          </div>
        </div>
      </div>
    </body>
  </main>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css" />
  </head>

  <main>
    <body>
      <div class="container">
      <div class="row">
          <div class="col-md-3">
            <%= render partial: 'users/show', locals: { user: @user }%>
            <%= render partial: 'books/new', locals: { book: @book }%>
          </div>

          <div class="col-md-8 offset-md-1">
            <h1 class="m-4">Users</h1>
            <table class="table">
                <tr>
                  <th> image </th>
                  <th> name </th>
                  <th></th>
                </tr>
              <% @users.each do |user| %>
                <div>
                  <tr>
                    <% if user.profile_image.attached? %>
                      <td><span class="book-title"><p><%= image_tag user.get_profile_image(100,100) %></p></td>
                    <% else %>
                      <td><span class="book-title"><p><%= image_tag 'no_image', size: '100x100' %></p></td>
                    <% end %>
                    <td><span class="book-title"><p><%= user.name %></p></td>
                    <td><span class="book-title"><p><%= link_to "Show", user_path(user.id) %></p></td>
                  </tr>
                </div>
              <% end %>
            </table>
          </div>
      </div>
    </body>
  </main>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css" />
  </head>

  <main>
    <body>
      <div class="container"> 
        <div class="row">
          <div class="col-md-3">
            <% if user_signed_in? %>
              <div>
                <h1 class="w-100 m-1 mt-4">User info</h1>
                  <% if @user.profile_image.attached? %>
                  <p><%= image_tag @user.get_profile_image(100,100) %></p>
                  <% else %>
                    <p><%= image_tag 'no_image', size: '100x100' %></p>
                  <% end %>
                  <h5 class="w-100 m-1">name<%= @user.name %></h5>
                  <h5 class="w-100 m-1">introduction<%= @user.introduction %></h5>
                  <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn w-50" do %>
                  <i class="fa-solid fa-user-gear"></i>
                  <% end %>
              </div>
            <% end %>
            <%= render partial: 'books/new', locals: { book: @book }%>
          </div>
          <div class="col-md-8 offset-md-1">
            <h1 class="mt-4">Books</h1>
            <table class="table">
                <tr>
                  <th></th>
                  <th>Title </th>
                  <th> Opinion</th>
                </tr>
                <% @books.each do |book| %>
                  <% if book.user.id == @user.id %>
                    <tr>
                      <td>
                      <% if book.user == current_user %>
                        <%= link_to user_path(book.user.id), onclick: "event.stopPropagation();" do %>
                          <span class="book-title"><p><%= image_tag book.user.get_profile_image(100,100) %></p>
                        <% end %>
                      <% else %>
                      <%= link_to user_path(book.user.id), onclick: "return false;" do %>
                          <span class="book-title"><p><%= image_tag book.user.get_profile_image(100,100) %></p>
                        <% end %> <% end %>
                      </td>
                      <td><span class="book-title"><p><%= link_to "#{book.title}", book_path(book.id)%></p></td>
                      <td><span class="book-title"><p><%= book.body %></p></td>
                    </tr>
                  <% end %>
                <% end %>
              </table>
          </div>
        </div>
      </div>
    </body>
  </main>
</html>